/* Angličtina — celý katalog, včetně klíčů sebraných z <body>.

   Závisí na: ničem
   Nezávisí na: DOM, úložišti, zbytku aplikace
   Je to DATA, ne kód: 467 klíčů. Strážní test sady 16 hlídá, že katalog
   pokrývá celou češtinu a nemění druh klíče (pole vs. řetězec). */
/* ---------- angličtina ----------
   Čeština se sbírá z <body> a doplňuje z RUCNI; každý další jazyk se píše
   celý sem. Klíče drží pořadí protějšku: nejdřív to, co stojí ve <body>,
   pak to, co vzniká za běhu. Strážní test hlídá, že katalog pokrývá
   češtinu klíč po klíči a že pole mají tvarů podle plural() daného jazyka.

   Čísla v pevných textech (tabulka pravidel, nabídka cílů) se nesázejí
   přes fmt() — jsou napsaná rovnou, a proto je tu oddělovač tisíců
   anglický. Formátovače dat a oddělovače pro fmt() leží výš u ostatních
   věcí, které textem nejsou. */
export var EN = {
  /* základní / rotace obrazovky */
  "titulek":  "Dice \u2014 counter",
  "wordmark": "Dice",
  "rot.nadpis": "Rotate your phone to portrait",
  "rot.text":   "The counter only works in portrait orientation.",

  /* nastavení hry */
  "hra.hrajese":   "playing",
  "hra.dobodu":    "to points",
  "hra.nakola":    "by turns",
  "hra.cil2000":   "2,000",
  "hra.cil4000":   "4,000",
  "hra.cil6000":   "6,000",
  "hra.cil8000":   "8,000",
  "hra.cil10000":  "10,000",
  "hra.vlastni":   "custom\u2026",
  "hra.neomezene": "unlimited",
  "hra.cil.aria":            "game goal",
  "hra.cilvlastni.aria":     "custom goal",
  "hra.limit.aria":          "round limit",
  "hra.limitvlastni.aria":   "custom round limit",

  /* záložky */
  "zalozka.pocitadlo":  "Counter",
  "zalozka.zapis":      "Turn log",
  "zalozka.statistiky": "Statistics",

  /* počítadlo */
  "pocitadlo.zapsano":       "banked",
  "pocitadlo.zbyva":         "remaining",
  "pocitadlo.zadat":         "enter",
  "pocitadlo.opravit":       "edit",
  "pocitadlo.zhodu":         "What you\u2019re keeping from the roll",
  "pocitadlo.stejne":        "Matching values",
  "pocitadlo.postupky":      "Straights",
  "pocitadlo.pridat":        "Add",
  "pocitadlo.hazetdal":      "Keep rolling",
  "pocitadlo.neuklada":      "Saving isn\u2019t working \u2014 the game in progress will be lost when you close the browser. Back up your history in Settings.",
  "pocitadlo.zpet":          "Undo",
  "pocitadlo.zapsatapredat": "Bank and pass",
  "pocitadlo.farkle":        "Farkle",
  "pocitadlo.body.ph":       "points",

  /* čipy klávesnice — malé písmeno stejně jako v češtině */
  /* Popisky čipů kombinací (2+2+2, 3+2, …) jsou jazykově neutrální a stojí
     v HTML bez anotace — překládají se jen názvy v nastavení a štítky
     v historii. */
  "pocitadlo.chip.rucne":    "custom",
  "pocitadlo.chip.rucnev":   "points",

  /* zápis kol */
  "zapis.nadpis":      "Turn log",
  "zapis.opravit":     "Edit",
  "zapis.prazdno":     "No turns yet. Roll all six dice.",
  "zapis.nicknulozeni": "Nothing to save to history yet",
  "zapis.novahra":     "New game",

  /* statistiky */
  "stat.nedostupna":     "History can\u2019t be loaded right now. Nothing has been lost \u2014 the app just can\u2019t reach it at the moment, so finished games aren\u2019t being saved yet. Try closing the app and opening it again.",
  "stat.seg.statistiky": "Statistics",
  "stat.seg.historie":   "Game history",
  "stat.zpetseznam":     "\u00AB Back",

  /* lišta filtrů */
  "filtr.datum":      "Date",
  "filtr.typ":        "Type",
  "filtr.razeni":     "Sort",
  "filtr.reset":      "Reset",
  "filtr.reset.aria": "Reset filters",

  /* pravidla */
  "pravidla.nadpis":        "Rules & how to play",
  "pravidla.seg.pravidla":  "Rules",
  "pravidla.seg.navod":     "How to play",

  /* návod */
  "rezim.n.kcd2":    "KCD",
  "rezim.n.klasika": "Classic farkle",
  "rezim.n.pet":     "Five dice",
  "rezim.pozn.kcd2":    "The weighted dice and badges from Kingdom Come: Deliverance II sit on top of the rules; the counter leaves them alone.",
  "rezim.pozn.klasika": "Piggyback is the same game with a different turn structure: instead of six fresh dice you may carry on from the dice and points the previous player left. Enter the points you take over by hand, with the <b>custom</b> chip.",
  "rezim.pozn.pet":     "Usually played to 5,000. Five of a kind on the first roll of a turn is often an instant win \u2014 keep an eye on that yourself, the counter doesn\u2019t know it.",
  "rezim.neznamy":   "unknown mode",
  "rezim.beznazvu":  "Custom mode",
  "rezim.postupek":  ["{n} straight", "{n} straights"],
  "rezim.kombinaci": ["{n} extra combination", "{n} extra combinations"],
  "rezim.pravidla":  "Rules",
  "rezim.upravit":   "Edit",
  "rezim.zvolit":    "Use this mode",
  "rezim.zvoleno":   "In use",
  "rezim.zamceno":   "The mode can only be switched before a game starts. Finish the game in progress, save it to the history and start a New game.",
  "rezim.strop":     "No more than {n} custom modes.",
  "rezim.opravdusmazat": "Really delete this mode?",
  "rezim.nesmazat":  "The mode in use can\u2019t be deleted. Pick another one first.",
  "rezim.nulaneboduje": "0 = doesn\u2019t score",
  "rezim.skupina.zapnout":  "Turn the whole group on",
  "rezim.skupina.vypnout":  "Turn the whole group off",
  "rezim.sam.n":     "A single die",
  "rezim.sam.p":     "What one die of that value is worth on its own.",
  "rezim.stej.2":    "Pairs",
  "rezim.stej.3":    "Three of a kind",
  "rezim.stej.4":    "Four of a kind",
  "rezim.stej.5":    "Five of a kind",
  "rezim.stej.6":    "Six of a kind",
  "rezim.stej.zapnout": "Turn matching numbers on",
  "rezim.stej.vypnout": "Turn matching numbers off",
  "rezim.rozs.zapnout": "Turn advanced mode on",
  "rezim.rozs.vypnout": "Turn advanced mode off",
  "rezim.aria.1":    "Points for a single {v}",
  "rezim.aria.2":    "Points for two {v}s",
  "rezim.aria.3":    "Points for three {v}s",
  "rezim.aria.4":    "Points for four {v}s",
  "rezim.aria.5":    "Points for five {v}s",
  "rezim.aria.6":    "Points for six {v}s",
  "rezim.nadn.3":    "Three or more of a kind",
  "rezim.nadn.4":    "Four or more of a kind",
  "rezim.nadn.5":    "Five or more of a kind",
  "rezim.nadn.6":    "Six of a kind",
  "rezim.zvolitkratce": "Use",
  "rezim.kopie":     "{n} (copy)",
  "rezim.dupl.n":    "Duplicate mode",
  "rezim.dupl.p":    "Makes a custom copy you can rebuild. The original stays as it is.",
  "rezim.dupl.btn":  "Duplicate",
  /* pás na spodní hraně detailu režimu — angličtina píše procento bez mezery */
  "rezim.riziko.n":  "Farkle risk",
  "rezim.riziko.pol": "{n}: {p}%",
  "rezim.riziko.pocita": "calculating…",
  "rezim.nad.info":  "What those rules mean",
  "rezim.nad.napoveda": "Say the highest group set is three of a kind and three 5s are worth 500. <b>Doubles</b>: four 5s 1,000, five 2,000, six 4,000. <b>Multiplies the group</b>: four 5s 1,000, five 1,500, six 2,000. <b>Fixed points</b>: the numbers below apply whatever the value.",
  "rezim.nadaria":   "Points for {n} of a kind",
  "rezim.nadpis":    "Game mode",
  "rezim.novy.n":    "Custom mode",
  "rezim.novy.p":    "Starts from the KCD rules and can be rebuilt completely.",
  "rezim.novy.btn":  "Add",
  "rezim.zpetseznam": "\u00AB Back",
  "rezim.nazev.n":   "Name",
  "rezim.nazev.p":   "The history shows the mode under this name.",
  "rezim.kostek.n":  "Number of dice",
  "rezim.kostek.p":  "How many dice you roll at the start of a turn and after hot dice.",
  "rezim.cap.post":  "Straights",
  "rezim.cap.sam":   "Single dice",
  "rezim.cap.stejna": "Matching numbers",
  "rezim.cap.vlastni": "Custom combinations",
  "rezim.cap.nastaveni": "Settings",
  "rezim.rozs.n":    "Advanced mode",
  "rezim.rozs.p":    "Splits matching numbers into pairs, triples, quads, quints and sextets separately.",
  "rezim.prah.n":    "From how many dice",
  "rezim.prah.p":    "How many matching numbers have to come up before they can be set aside.",
  "rezim.nad.n":     "Rule above the highest group",
  "rezim.nad.p":     "What each further die above the highest group set does.",
  "rezim.nad.x2":    "doubles",
  "rezim.nad.nasobek": "multiplies the group",
  "rezim.nad.pevne": "fixed points",
  "rezim.vychozi.n": "Restore defaults",
  "rezim.vychozi.p": "Throws away every change made to this mode.",
  "rezim.vychozi.btn": "Restore",
  "rezim.smazat.n":  "Delete mode",
  "rezim.smazat.p":  "Games already in the history keep their name.",

  /* sharing individual game modes */
  "rezim.pridano":          ["{n} mode added.", "{n} modes added."],
  "rezim.sdil.vyber":       "Pick at least one game mode.",
  "rezim.sdil.vybrano":     "Selected",
  "rezim.sdil.nevybrano":   "Not selected",
  "rezim.imp.duplicitni":   "“{n}” already has the same rules \u2014 this one won\u2019t be added.",
  "rezim.imp.prejmenovano": "Renamed because of a matching name.",
  "rezim.imp.nic":          "Nothing to import \u2014 every mode was skipped.",

  "pravidla.p1":    "You roll {kostky} and set aside at least one scoring die or combination. If the roll scores nothing at all, it\u2019s a <b>Farkle</b> \u2014 everything you have on the table this turn is lost and the turn passes on.",
  "pravidla.p2":    "After every roll you decide: <b>bank</b> the points and pass the turn, or <b>keep rolling</b> with just the dice you haven\u2019t set aside.",
  "pravidla.p3":    "Set aside even the last die and you get <b>hot dice</b> \u2014 you roll {kostky} again and the points keep adding up in the same turn.",
  "pravidla.sam.1": "Every 1",
  "pravidla.sam.2": "Every 2",
  "pravidla.sam.3": "Every 3",
  "pravidla.sam.4": "Every 4",
  "pravidla.sam.5": "Every 5",
  "pravidla.sam.6": "Every 6",
  "pravidla.dvoj.1": "Two 1s",
  "pravidla.dvoj.2": "Two 2s",
  "pravidla.dvoj.3": "Two 3s",
  "pravidla.dvoj.4": "Two 4s",
  "pravidla.dvoj.5": "Two 5s",
  "pravidla.dvoj.6": "Two 6s",
  "pravidla.t4n":   "Three 2s / 3s / 4s / 5s / 6s",
  "pravidla.troj.1": "Three 1s",
  "pravidla.troj.2": "Three 2s",
  "pravidla.troj.3": "Three 3s",
  "pravidla.troj.4": "Three 4s",
  "pravidla.troj.5": "Three 5s",
  "pravidla.troj.6": "Three 6s",
  "pravidla.stejnych.3": "Three of a kind",
  "pravidla.stejnych.4": "Four of a kind",
  "pravidla.stejnych.5": "Five of a kind",
  "pravidla.stejnych.6": "Six of a kind",
  "pravidla.post.15": "1\u20135 straight",
  "pravidla.post.26": "2\u20136 straight",
  "pravidla.post.16": "1\u20136 straight",
  "pravidla.nicneboduje": "Nothing scores in this mode",
  "pravidla.pozn2": "\u201CAlmost\u201D counts for nothing \u2014 you can only set aside what the table lists whole.",

  "komb.nevejde":   "more dice than the mode has",
  "komb.bezvzoru":  "no pattern yet — won’t show on the counter",
  "pocitadlo.postupkykomb": "Straights and combinations",
  "pocitadlo.kombinace":    "Combinations",
  "stat.n.rezim":   "Most played mode",

  "navod.kolo.h":   "Turn",
  "navod.kolo.p":   "The keypad records what you set aside from the roll. Points add up in the <b>table</b> row and the dice you used drop out of the remaining ones.",
  "navod.kolo.li1": "<b>Keep rolling</b> \u2014 opens a new roll and its label says how many dice with. Once all six are set aside, it offers hot dice and you roll all six again.",
  "navod.kolo.li2": "<b>Bank</b> \u2014 moves the points from the table into the score and opens a new turn.",
  "navod.kolo.li3": "<b>Farkle</b> \u2014 the points on the table are lost and the log keeps a turn worth zero.",
  "navod.kolo.li4": "<b>Risk</b> \u2014 the number shown right on the Farkle button (e.g. \u201cFarkle 3.1%\u201d) is the chance that the next roll scores nothing. It\u2019s recalculated after every roll, based on how many dice are left.",
  "navod.klavesnice.h":    "Keypad",
  "navod.klavesnice.p":    "<b>single 1</b> and <b>single 5</b> add one die at a time. <b>Matching values</b> take the count in the first row and the value in the second; the button on the right shows the result and adds it. <b>Straights</b> are three fixed combinations. <b>manual</b> opens a field for points and arrows for the number of dice.",
  "navod.klavesnice.pozn": "Combinations that don\u2019t fit into the remaining dice are greyed out.",
  "navod.opravy.h":  "Corrections",
  "navod.opravy.p1": "The <b>enter / edit</b> switch beside the roll description flips the inner card of the panel. The <i>edit</i> card shows every set-aside item as a button with a cross, grouped by rolls; deleting an item also recounts the dice in the rolls that follow.",
  "navod.opravy.p2": "<b>Undo</b> takes back one step at a time from the end of the current turn \u2014 items first, then whole rolls. It doesn\u2019t touch banked turns; once nothing is left in the turn, the button greys out.",
  "navod.opravy.p3": "<b>Edit</b> in the Turn log switches on the crosses beside individual turns. A cross asks for confirmation; a deleted turn is subtracted from the score and the remaining turns are renumbered. With no turns played the button is hidden.",
  "navod.hra.h": "Game settings",
  "navod.hra.p": "The dice icon opens the panel with the mode and the target, even in the middle of a game. <b>To points</b> plays to 2,000 up to 10,000 or to a number of your own, and the second row of the score shows how much is left. The turn that crosses the target counts in full; once it is banked, the game is over. <b>By turns</b> only counts turns; an optional limit locks the game after the last one, without a limit the game never ends by itself.",
  "navod.rezimy.h":  "Game modes",
  "navod.rezimy.p1": "Farkle is played in several versions and each one scores differently. The <b>game mode</b> in the settings holds the whole table: how many dice you roll, what a single 1, a single 5 and each three of a kind are worth, what the fourth and further matching dice do, which straights score and which extra combinations are on. Three come ready-made \u2014 <i>KCD</i>, <i>Classic farkle</i> and <i>Five dice</i>; you can add twenty of your own and rebuild any of them completely.",
  "navod.rezimy.p2": "<b>Rules</b> next to a mode shows its table, <b>Edit</b> opens its settings and <b>Use this mode</b> puts it into play. Extra combinations and custom patterns always belong to one mode, not to the app \u2014 switching modes swaps them too. While editing a mode, a bust-risk band for every remaining-dice count is shown at the bottom \u2014 it helps judge whether the edited rules make sense.",
  "navod.rezimy.p3": "The mode can only be switched with nothing in progress: one turn scored under one set of rules and the next under another would add up to nothing meaningful. So finish the game in progress and start a <b>New game</b>. Every game carries its mode into the history, and the <i>Most played mode</i> statistic counts which one wins.",
  "navod.rezimy.p4": "Individual modes can also be sent outside a backup: <b>Share selected</b> sends the chosen modes as text (save to a file or copy it to the clipboard), <b>Import</b> reads such text back from a file or the clipboard. A shared mode is always created as a new custom mode \u2014 if it\u2019s identical to an existing one, the import skips it; if only the name collides, it renames it.",
  "navod.stranky.h":   "Three pages",
  "navod.stranky.p":   "The tabs at the top and a swipe sideways switch between:",
  "navod.stranky.li1": "<b>Counter</b> \u2014 the score and the playing.",
  "navod.stranky.li2": "<b>Turn log</b> \u2014 four figures and the table of turns, New game and Save to history.",
  "navod.stranky.li3": "<b>Statistics</b> \u2014 a switch between the records and the list of finished games. A record opens into a leaderboard, a game into its detail. The game list can also be filtered by date (and by game type, if history has more than one) and sorted; <b>Reset</b> returns filters and sorting to their defaults.",
  "navod.historie.h":  "History",
  "navod.historie.p1": "The statistics come only from games in history; a game you don\u2019t save leaves no mark on the records.",
  "navod.historie.p2": "<b>Save to history</b> asks for a second tap only when there are unbanked points on the table. Once saved it turns into <b>Saved to history</b>, and after more play into <b>Update in history</b>, which overwrites the same record instead of starting a new one. If that game gets deleted from history in the meantime, the button offers <b>Restore to history</b> \u2014 it brings the same record back from the trash, so a game is never written down twice.",
  "navod.historie.p3": "<b>Autosave</b> in the settings writes the game into history by itself as soon as it ends \u2014 after the last turn, or after the turn that crosses the target. A little window that disappears on its own announces it. A game on an unlimited number of turns can\u2019t be saved this way, because it has no end. What was deleted from history by hand, autosave never brings back.",
  "navod.kos.h":  "Trash",
  "navod.kos.p1": "<b>New game</b> puts the deleted game into the settings, into <i>Deleted games in progress</i> \u2014 the last five are kept. <b>Delete from history</b> puts the game into <i>Games deleted from history</i>, where ten of them stay. In both sections the <i>Restore</i> button brings a game back; <i>Delete permanently</i> throws it away for good once confirmed.",
  "navod.kos.p2": "When a game isn\u2019t in history yet, <b>New game</b> asks once more after the confirmation and offers to save it right away.",
  "navod.zaloha.h": "Backup",
  "navod.zaloha.p1": "The data lives only in this browser. <b>Export to file</b> makes a text file with an overview of the games whose last line carries the data for the import \u2014 without it the file can\u2019t be read back. <b>Copy to clipboard</b> gives the same content without downloading. Both <b>Import from file</b> and <b>Import from clipboard</b> offer a choice between adding the new games and replacing the whole history.",
  "navod.zaloha.p2": "<b>Complete backup</b> backs up history and all game modes together, in one file. <b>Game modes backup</b> backs up just the modes, without history. Both work like the history backup \u2014 file or clipboard, add or <b>Replace all</b> \u2014 but replacing modes only works when no game is in progress, since the active game reads rules from them live. Sending just a few chosen modes elsewhere is separate \u2014 described above under Game modes.",
  "navod.zaloha.p3": "Settings also show <b>Space used</b> at the bottom: how much data the app takes up on the device. Expanding it (<b>Detail</b>) breaks it down into history, the in-progress game, both trash bins, and remaining settings, plus a total for the whole address \u2014 which also counts anything unrelated to Farkle. The number is computed only on request, not continuously.",
  "navod.drobnosti.h": "Odds and ends",
  "navod.drobnosti.p0": "<b>Language</b>, at the top of settings, switches the interface between Czech and English instantly, without restarting the app.",
  "navod.drobnosti.p": "The icon in the top right switches the light and dark look. <b>Full screen</b> in the settings hides the browser bars; on an iPhone it isn\u2019t there, Safari can\u2019t do it. <b>Keep screen on</b> in the same place holds the screen lit while the game runs; after three minutes without a touch it lets go and the phone goes dark as usual. The app works offline and can be added to the home screen.",

  /* nastavení */
  "nast.nadpis":        "Settings",
  "nast.jazyk.n":       "Language",
  "nast.jazyk.p":       "Changes at once, without restarting the app.",
  "nast.jazyk.aria":    "Interface language",
  "nast.fs.n":          "Full screen",
  "nast.fs.p":          "Hides the browser bars.",
  "nast.vypnuto":       "Off",
  "nast.svit.n":        "Keep screen on",
  "nast.svit.p":        "The screen stays lit while the app is in use. After three minutes without a touch it lets go and the phone goes dark as usual.",
  "nast.auto.n":        "Autosave",
  "nast.auto.p":        "Writes the game into history as soon as it ends. A game on an unlimited number of turns isn\u2019t saved automatically.",
  "nast.koshry":        "Deleted games in progress",
  "nast.koshist":       "Games deleted from history",
  "nast.zaloha":        "History backup",
  "nast.exp.n":         "Export to file",
  "nast.exp.p":         "A text file with an overview of the games and the data for a later import.",
  "nast.exp.btn":       "Save",
  "nast.kop.n":         "Copy to clipboard",
  "nast.kop.p":         "In case downloading doesn\u2019t work.",
  "nast.kop.btn":       "Copy",
  "nast.impf.n":        "Import from file",
  "nast.impf.p":        "Reads a backup and offers to add or to replace.",
  "nast.impf.btn":      "Choose file",
  "nast.imps.n":        "Import from clipboard",
  "nast.imps.p":        "Paste the backup text into the field and read it in.",
  "nast.imps.btn":      "Paste text",
  "nast.vlozit.ph":     "Paste the copied backup here",
  "nast.nacist":        "Load",
  "nast.pridatnove":    "Add new",
  "nast.nahraditvse":   "Replace all",
  "nast.seg.obecne":    "General",
  "nast.seg.rezimy":    "Game modes",
  "nast.seg.zalohy":    "Backups",
  "nast.komb":          "Extra combinations",
  "komb.novy.n":        "Custom combination",
  "komb.novy.p":        "Tapped in die by die; it can score through several patterns at once.",
  "komb.novy.btn":      "Add",
  "komb.nazev.n":       "Name",
  "komb.nazev.p":       "The chip and the rules show the combination under this name.",
  "komb.cap.vzory":     "Patterns",
  "komb.cap.novyvzor":  "New pattern",
  "komb.zpetrezim":     "« Back",
  "komb.pridatvzor":    "Add pattern",
  "komb.cap.cisla":     "Exact values",
  "komb.cap.pismena":   "Any, but matching",
  "komb.pismena.p":     "The same letter means the same value. Each letter lands on a different value, and on a different one than the numbers in the pattern.",
  "komb.vymazat":       "Clear",
  "nast.misto.n":       "Storage used",
  "nast.misto.zjistuji": "Checking\u2026",
  "nast.misto.btn":     "Detail",

  /* karta Zálohy: kompletní záloha a záloha herních režimů */
  "nast.zalplna":       "Complete backup",
  "nast.expplna.n":     "Export to file",
  "nast.expplna.p":     "A text file with the history and the game modes for a later import.",
  "nast.expplna.btn":   "Save",
  "nast.kopplna.n":     "Copy to clipboard",
  "nast.kopplna.p":     "In case downloading doesn’t work.",
  "nast.kopplna.btn":   "Copy",
  "nast.impfplna.n":    "Import from file",
  "nast.impfplna.p":    "Reads a complete backup and offers to add or to replace.",
  "nast.impfplna.btn":  "Choose file",
  "nast.impsplna.n":    "Import from clipboard",
  "nast.impsplna.p":    "Paste the complete backup text into the field and read it in.",
  "nast.impsplna.btn":  "Paste text",
  "nast.zalrez":        "Game mode backup",
  "nast.exprez.n":      "Export to file",
  "nast.exprez.p":      "A text file with all game modes for a later import.",
  "nast.exprez.btn":    "Save",
  "nast.koprez.n":      "Copy to clipboard",
  "nast.koprez.p":      "In case downloading doesn’t work.",
  "nast.koprez.btn":    "Copy",
  "nast.impfrez.n":     "Import from file",
  "nast.impfrez.p":     "Reads a game mode backup and offers to add or to replace.",
  "nast.impfrez.btn":   "Choose file",
  "nast.impsrez.n":     "Import from clipboard",
  "nast.impsrez.p":     "Paste the game mode backup text into the field and read it in.",
  "nast.impsrez.btn":   "Paste text",

  /* sdílení jednotlivých herních režimů */
  "rezim.sdil.n":       "Share selected",
  "rezim.sdil.p":       "Sends one or more game modes to another device.",
  "rezim.sdil.btn":     "Share",
  "rezim.imp.n":        "Import",
  "rezim.imp.p":        "Reads a sharing code from a file or the clipboard and offers to add it.",
  "rezim.imp.btn":      "Import",
  "rezim.imp.potvrdit": "Import selected",

  /* okna filtrů a nové hry */
  "datum.nadpis":     "Filter by date",
  "datum.jedenden":   "One day",
  "datum.rozsah":     "Range",
  "datum.den":        "Day",
  "datum.do":         "To",
  "typ.nadpis":       "Filter by game type",
  "typ.vse":          "All",
  "typ.nabody":       "To points",
  "typ.nakola":          "By turns",
  "typ.cil":          "Target",
  "razeni.nadpis":    "Sort history",
  "razeni.nejnovejsi": "Newest first",
  "razeni.nejstarsi": "Oldest first",
  "razeni.nejvic":    "Most points first",
  "razeni.nejmin":    "Fewest points first",
  "nova.nadpis":      "The game isn\u2019t saved",
  "nova.ulozit":      "Save and start a new one",
  "nova.bezulozeni":  "Start a new one without saving",

  /* společné */
  "spol.zpet":    "Back",
  "spol.zrusit":  "Cancel",
  "spol.pouzit":  "Apply",
  "spol.zavrit":  "Close",
  "spol.smazat":  "Delete",
  "spol.obnovit": "Restore",
  "spol.zapnuto": "On",

  /* hlavička okna */
  "hlav.nastavenihry": "Game settings",
  "hlav.pravidla":     "Rules",
  "hlav.nastaveni":    "Settings",
  "hlav.svetlyrezim":  "Light mode",
  "hlav.tmavyrezim":   "Dark mode",

  /* slova s více tvary — angličtina má dva */
  "slovo.kolo":     ["{n} turn", "{n} turns"],
  "slovo.hra":      ["{n} game", "{n} games"],
  "slovo.nova":     ["{n} new", "{n} new"],
  "slovo.rezim":    ["{n} mode", "{n} modes"],
  "slovo.kostkami": ["{n} die", "{n} dice"],
  "slovo.kostek":   ["{n} die", "{n} dice"],
  "slovo.farkle":   "farkle",

  /* štítky odložených položek */
  "stitek.j":   "single 1",
  "stitek.p":   "single 5",
  "stitek.d2":  "single 2",
  "stitek.d3":  "single 3",
  "stitek.d4":  "single 4",
  "stitek.d6":  "single 6",
  "stitek.v":   "custom",
  "stitek.s15": "1\u20135 straight",
  "stitek.s26": "2\u20136 straight",
  "stitek.s16": "1\u20136 straight",
  "stitek.n":   "{p}\u00D7 {h}",

  "stitek.c2p": "two pairs",
  "stitek.c3p": "three pairs",
  "stitek.c32": "triple and pair",
  "stitek.c33": "two triples",
  "stitek.c42": "quad and pair",
  "stitek.k":   "custom {b} · {d}",

  /* režim hry */
  "typhry.dobodu":      "to {b}",
  "typhry.nakola":      "by turns",
  "typhry.nakolalimit": "by turns \u00B7 limit {n}",

  /* počítadlo za běhu */
  "pocitadlo.kolonastole": "Turn {n} \u2014 on the table",
  "pocitadlo.odehranokol": "turns played",
  "pocitadlo.nadcil":      "over target",
  "pocitadlo.zkol":        "{n} of {z}",
  "pocitadlo.hodradek":    "Roll {n} \u2014 rolling <b>{kostky}</b>",
  "pocitadlo.hodzbyva":    "\u00B7 {n} left",
  "pocitadlo.hraskoncila": "Game over \u2014 show the turn log",
  "pocitadlo.nejdriv":     "Set something aside from the roll first",
  "pocitadlo.hazetdalx":   "Keep rolling \u2014 {kostky}",
  "pocitadlo.horke":       "Hot dice \u2014 roll all six again",
  "pocitadlo.zapsatx":     "Bank {b}",
  "pocitadlo.plus":        "+ {b}",
  "pocitadlo.kostzkr":     ["{n} die", "{n} dice"],
  "pocitadlo.konecbody":   "The target of {b} is reached \u2014 the game is over. The target can be changed in the game settings.",
  "pocitadlo.koneckola":   "All {n} turns are played \u2014 the game is over. The number of turns can be changed in the game settings.",

  /* riziko farklu na tlačítku Farkle — angličtina píše procento bez mezery */
  "pocitadlo.farkleriziko": "risk {p}%",

  /* kombinace navíc v nastavení */
  "komb.zapnout":       "Turn the combination on",
  "komb.vypnout":       "Turn the combination off",
  "komb.sazba":         "Points for the combination",
  "komb.zadne":         "No custom combination yet.",
  "komb.naukej":        "Tap in the dice the combination is made of.",
  "komb.strop":         "No more than {n} custom combinations.",
  "komb.opravdusmazat": "Really delete the combination?",
  "komb.vychozin":      "Combination {n}",
  "komb.beznazvu":      "Custom combination",
  "komb.body.n":        "Points",
  "komb.body.p":        "Worth the same whichever pattern lands.",
  "komb.stav.n":        "State",
  "komb.stav.p":        "A combination that is off leaves the keypad and doesn\u2019t change the farkle risk.",
  "komb.smazat.n":      "Delete combination",
  "komb.smazat.p":      "Games already in the history keep their label.",
  "komb.opravdusmazatvzor": "Really delete this pattern?",
  "komb.stropvzoru":    "No more than {n} patterns in one combination.",
  "komb.vyberkostek":   "how many dice?",

  /* slovník pro nazevTvaru() — musí vyrobit i názvy presetů:
     three pairs, triple and pair, two triples, quad and pair */


  /* vrubovka */
  "tally.kolzn":     "turns played: {n} of {z}",
  "tally.koln":      "turns played: {n}",
  "tally.zadnekolo": "no turns yet",
  "tally.docile":    "{b} left to the target",
  "tally.prekonano": "target beaten by {b}",

  /* karta opravit a tabulka kol */
  "oprava.nic":           "Nothing recorded in this turn yet.",
  "oprava.hod":           "roll {n} \u00B7 {k}d",
  "oprava.horke":         "hot",
  "oprava.smazatpolozku": "Delete item",
  "zapis.hotovo":         "Done",
  "zapis.opravdusmazat":  "Really delete turn {n}?",
  "zapis.smazatkolo":     "Delete turn {n}",

  /* přehledové dlaždice */
  "souhrn.celkem":   "total",
  "souhrn.nejlepsi": "best",
  "souhrn.prumer":   "average",
  "souhrn.farklu":   "farkles",

  /* tlačítko zápisu do historie */
  "arch.propadne":     "There is {b} on the table and it will be lost \u2014 bank it?",
  "arch.obnovit":      "Restore to history",
  "arch.ulozeno":      "Saved to history",
  "arch.aktualizovat": "Update in history",
  "arch.zapsat":       "Save to history",

  /* hlášky o selhání zápisu */
  "chyba.mistoulozit":  "Couldn\u2019t save \u2014 out of storage",
  "chyba.mistosmazat":  "Couldn\u2019t delete \u2014 out of storage",
  "chyba.nedostupna":   "History isn\u2019t available right now",
  "chyba.zalohovathru": "Couldn\u2019t back up the game in progress",
  "chyba.smazat":       "Couldn\u2019t delete",
  "chyba.dokose":       "Couldn\u2019t move to the trash",

  /* koš */
  "kos.opravdutrvale": "Delete permanently?",
  "kos.trvalesmazat":  "Delete permanently",
  "kos.prazdny":       "Nothing to restore yet. A game deleted with the New game button lands here by itself.",
  "kos.prazdnyhist":   "Nothing to restore yet. A game deleted from history lands here by itself.",

  /* nová hra */
  "nova.nezalohovano": "Couldn\u2019t back it up \u2014 the game stays",
  "nova.opravdu":      "Really a new one?",
  "nova.text":         "This game isn\u2019t in history yet, so it won\u2019t count towards the statistics. " +
                       "A new game puts it into the settings, among the deleted games in progress \u2014 the last five are kept.",
  "nova.propadne":     "There is {b} on the table and it will be lost.",

  /* bublina */
  "toast.aktualizovan": "Record in history updated",
  "toast.ulozena":      "Game saved to history",

  /* stavové popisky přepínačů */
  "fs.zpet":         "Leave full screen",
  "fs.zapnout":      "Full screen",
  "svit.nechat":     "Let the screen go dark",
  "svit.nezhasinat": "Keep screen on",
  "auto.vypnout":    "Turn autosave off",
  "auto.zapnout":    "Turn autosave on",

  /* názvy sledovaných statistik */
  "stat.n.pocet":        "Games played",
  "stat.n.denmax":       "Most games in a day",
  "stat.n.soucet":       "Points collected in total",
  "stat.n.maxbody":      "Most points in a game",
  "stat.n.maxbodybody":  "Most points \u2014 game to points",
  "stat.n.maxbodykola":  "Most points \u2014 game by turns",
  "stat.n.prumer":       "Overall average per turn",
  "stat.n.prumerbody":   "Average per turn \u2014 game to points",
  "stat.n.prumerkola":   "Average per turn \u2014 game by turns",
  "stat.n.maxhodu":      "Most rolls in one turn",
  "stat.n.minkol":       "Fewest turns in one game to points",
  "stat.n.maxkol":       "Most turns in one game to points",
  "stat.n.nejlepsikolo": "Best turn",
  "stat.n.nejhorsikolo": "Worst turn without a farkle",
  "stat.n.maxfarklu":    "Most farkles in a game",
  "stat.n.farkleprvni":    "First-roll farkles in total",
  "stat.n.maxfarkleprvni": "Most first-roll farkles in a game",
  "stat.n.ztraceno":     "Most points lost to a farkle",
  "stat.n.serie":        "Longest run without a farkle",
  "stat.n.farkluhra":    "Farkles per game",

  /* seznamy statistik a historie */
  "stat.filtrprazdno": "No game matches this filter.",
  "stat.zadnahra":     "No finished game yet. A game goes into history with the button at the bottom of the Turn log.",
  "stat.beznadat":     "There is no data for this statistic yet.",
  "hist.prazdna":      "History is empty. A finished game goes into it with the button at the bottom of the Turn log.",
  "hist.farklex":      "{n}\u00D7 farkle",
  "hist.hraz":         "Game from {kdy}",
  "hist.nactamkola":   "Loading turns\u2026",
  "hist.kolanejdou":   "The turns of this game can\u2019t be loaded right now.",
  "hist.zadnekolo":    "No turn is recorded in this game.",
  "hist.smazat":       "Delete from history",
  "hist.opravdu":      "Really delete?",

  /* dolití dlouhého seznamu */
  "dalsi.dalsich":    "Show {n} more",
  "dalsi.zbyva":      "{n} left",
  "dalsi.poslednich": "Show the last {n}",

  /* lišta filtrů za běhu */
  "filtr.typhry":    "Game type",
  "filtr.nabody":    "to points",
  "filtr.nakolan":   "by turns \u00B7 {n}",
  "filtr.bezlimitu": "no limit",
  "datum.od":        "From",
  "typ.limit":       "Limit",
  "typ.vsechny":     "All",

  /* záloha a import */
  "zal.pripravuji":       "Preparing the backup\u2026",
  "zal.neslozit":         "The backup couldn\u2019t be put together \u2014 history isn\u2019t available right now.",
  "zal.opravdunahradit":  "Really replace?",
  "zal.ukladase":         "The file is being saved.",
  "zal.stazenineslo":     "The download failed \u2014 try the copy to the clipboard.",
  "zal.veschrance":       "The backup is on the clipboard.",
  "zal.schrankaneslo":    "Copying to the clipboard failed \u2014 try Export to file.",
  "zal.souborneslo":      "The file couldn\u2019t be read.",
  "zal.poleprazdne":      "The field is empty \u2014 paste the backup text into it.",
  "zal.nerozumim.soubor": "The file makes no sense \u2014 the data line is missing.",
  "zal.nerozumim.text":   "The text makes no sense \u2014 the data line is missing.",
  "zal.prazdno.soubor":   "There is no game in the file.",
  "zal.prazdno.text":     "There is no game in the text.",
  "zal.info.soubor":      "The file holds {her}, {nove} of them.",
  "zal.info.text":        "The text holds {her}, {nove} of them.",
  "zal.pridatn":          "Add {n}",
  "zal.nenicopridat":     "Nothing to add",
  "zal.pridano":          ["{n} game added.", "{n} games added."],
  "zal.nahrazeno":        "History replaced, {her}.",

  /* čitelná část souboru zálohy */
  "exp.nadpis":     "Dice \u2014 backup of the game history",
  "exp.vytvoreno":  "created {kdy}, games: {n}",
  "exp.souhrn":     "total {b}, best turn {nej}, farkles {f}",
  "exp.mezisoucet": "total {b}",
  "exp.oddelovac":  "--- data for the import, do not touch ---",

  /* complete backup and game mode backup */
  "expplna.nadpis":     "Dice \u2014 complete backup",
  "expplna.vytvoreno":  "created {kdy}, {her}, {rez}",
  "exprez.nadpis":      "Dice \u2014 game mode backup",
  "exprez.vytvoreno":   "created {kdy}, {n}",
  "sdil.nadpis":        "Dice \u2014 shared game modes",
  "sdil.vytvoreno":     "created {kdy}, {n}",
  "zalplna.info.soubor":    "The file contains {her} and {rez}.",
  "zalplna.info.text":      "The text contains {her} and {rez}.",
  "zalplna.pridano":        "Added: {her}, {rez}.",
  "zalplna.nahrazeno":      "Complete backup restored, {her}, {rez}.",
  "zalrez.info.soubor":     "The file contains {rez}.",
  "zalrez.info.text":       "The text contains {rez}.",
  "zalrez.nahrazeno":       "Game modes replaced, {rez}.",
  "zal.rezimyzamceno":      "Game modes can\u2019t be replaced in the middle of a game. Finish or discard the game and try again.",

  /* zabrané místo */
  "misto.nezjistit":    "The size can\u2019t be found out.",
  "misto.zdostupnych":  "{u} of {q} available",
  "misto.pocitam":      "Counting\u2026",
  "misto.historie":     "History:",
  "misto.nezmeritmalo": "the size can\u2019t be found out",
  "misto.priblizne":    "about {v}",
  "misto.zadnahra":     "no game yet",
  "misto.rozehrana":    "Game in progress:",
  "misto.nezmerit":     "can\u2019t be measured",
  "misto.kose":         "Trash:",
  "misto.prazdne":      "empty",
  "misto.nastaveni":    "Settings and older data:",
  "misto.aplikace":     "App:",
  "misto.offline":      "{v}, kept for running offline",
  "misto.celkem":       "Total from this address:",
  "misto.trvale":       "The browser has marked it as permanent."
};
